version: "3.5"

services:
  node:
    build:
      context: .
    container_name: node
    depends_on:
      - postgres
    ports:
      - 4000:4000
    volumes:
      - ./:/app/

  postgres:
    container_name: postgres
    image: postgres:10.6
    ports:
      - 5442:5432
    volumes:
      - ./service-files:/docker-entrypoint-initdb.d/
