name: secret_diary_backend
version: 0.0.1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:

  args: ^1.4.2
  shelf: ^0.7.2
  dotenv: ^1.0.0
  jaguar_jwt: ^2.1.6
  postgres: 2.1.1

  flutter_simple_dependency_injection: ^1.0.2+1

  proto_module:
    git:
      url: https://github.com/NR-inc/secret-diary-backend.git
      ref: dart-grpc/develop
      path: proto_module